version: '3.9'

services:

  frontend:
    build: ./fgs-frontend
    container_name: frontend-service
    env_file:
      - ./fgs-frontend/.env
    depends_on:
      - identity
      - products
    ports:
      - "3000:3000"
    networks:
      - fgs-network

  identity:
    build: ./fgs-identity-management
    container_name: identity-service
    env_file:
      - ./fgs-identity-management/.env
    depends_on:
      - redis
      - mongo
    ports:
      - "3001:3000"
    networks:
      - fgs-network

  products:
    build: ./fgs-products
    container_name: products-service
    env_file:
      - ./fgs-products/.env
    depends_on:
      - mongo
      - redis
    ports:
      - "3002:3000"
    networks:
      - fgs-network

  mongo:
    image: mongo:7
    container_name: mongo-local
    restart: always
    ports:
      - "${MONGO_PORT:-27017}:27017"
    volumes:
      - mongo_data:/data/db
    networks:
      - fgs-network

  redis:
    image: redis:7
    container_name: redis-local
    restart: always
    command: redis-server --requirepass ${REDIS_PASSWORD}
    ports:
      - "${REDIS_PORT:-6379}:6379"
    volumes:
      - redis_data:/data
    networks:
      - fgs-network

volumes:
  mongo_data:
  redis_data:

networks:
  fgs-network:
    driver: bridge
